# Generated by Django 4.0.3 on 2022-04-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0003_carbrand_carmodel_usercar'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercar',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
